### ISSUE TITLE
[7] Resolve Technical Debt(s) - Javier Sandoval Gonzales

### ISSUE THREAD

**Issue by thanhpd** [thanhpd/OpenTracks-Winter-SOEN-6431_2024#12]
- Analyze
- Provide your work in the draft submission document
- Ask for feedback
- Update based on the provided feedback
- Repeat until it's done

![Image](https://github.com/thanhpd/OpenTracks-Winter-SOEN-6431_2024/assets/6737911/9748a474-5d96-4d3d-a13d-ac30e9637a00)

**Comment by jaedusandoval** [comment]
This issue will be closed, because there are two issues created and associated with the correction of technical debt for team member Javier Sandoval
