### ISSUE TITLE
[4a] List the main functionality provided by your code

### ISSUE THREAD

**Issue by thanhpd** [thanhpd/OpenTracks-Winter-SOEN-6431_2024#2]
- Analyze
- Provide your work in the draft submission document
- Ask for feedback
- Update based on the provided feedback
- Repeat until it's done

![image](https://github.com/thanhpd/OpenTracks-Winter-SOEN-6431_2024/assets/6737911/f66c804b-cc95-4d36-9c44-755c5d1f4c76)

**Comment by gs205436** [comment]
[4AReport.pdf](https://github.com/thanhpd/OpenTracks-Winter-SOEN-6431_2024/files/14231181/4AReport.pdf)


Above is the analysis report attached  FYI. @thanhpd  . Please provide your feedback if any other things we need to add in this document
